// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:kaiplay/core/storage/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(DailyDrawStateStorageModelAdapter());
    registerAdapter(GameStorageModelAdapter());
    registerAdapter(PlayHistoryStorageModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(DailyDrawStateStorageModelAdapter());
    registerAdapter(GameStorageModelAdapter());
    registerAdapter(PlayHistoryStorageModelAdapter());
  }
}
